# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinRegModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_features', models.IntegerField(max_length=50)),
                ('model_file', models.FileField(upload_to='models/linreg/')),
                ('feature_list', models.CharField(max_length=1000)),
                ('model_name', models.CharField(max_length=1000, unique=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
