# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linregmodel',
            name='num_features',
            field=models.IntegerField(),
        ),
    ]
