# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linreg', '0002_auto_20170509_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='linregmodel',
            name='csv_file',
            field=models.FileField(default='a', upload_to='models/linreg/csv/'),
            preserve_default=False,
        ),
    ]
